organisation:
  ods_code: AJC

team:
  workgroup: vaccsukbarnetsais
  name: Vaccination UK - Barnet
  email: barnet@v-uk.co.uk
  phone: "0208 150 7505"
  careplus_venue_code: UNKNOWN
  privacy_policy_url: https://www.schoolvaccination.uk/policies
  privacy_notice_url: https://www.schoolvaccination.uk/policies
  reply_to_id: dc2d30a6-0678-4c91-b37c-4790c279ab1c
  type: poc_only

programmes: [menacwy, mmr, td_ipv, hpv]

subteams:
  barnet:
    name: Vaccination UK - Barnet
    email: barnet@v-uk.co.uk
    phone: "0208 150 7505"
    reply_to_id: dc2d30a6-0678-4c91-b37c-4790c279ab1c

schools:
  barnet:
    - 101251
    - 101252
    - 101253
    - 101254
    - 101255
    - 101258
    - 101262
    - 101263
    - 101264
    - 101266
    - 101269
    - 101270
    - 101271
    - 101272
    - 101274
    - 101277
    - 101278
    - 101279
    - 101280
    - 101281
    - 101282
    - 101283
    - 101285
    - 101286
    - 101289
    - 101290
    - 101293
    - 101294
    - 101295
    - 101296
    - 101298
    - 101299
    - 101301
    - 101304
    - 101309
    - 101311
    - 101312
    - 101313
    - 101314
    - 101315
    - 101316
    - 101317
    - 101318
    - 101319
    - 101321
    - 101323
    - 101324
    - 101325
    - 101326
    - 101327
    - 101328
    - 101329
    - 101330
    - 101331
    - 101332
    - 101333
    - 101334
    - 101335
    - 101337
    - 101338
    - 101339
    - 101340
    - 101341
    - 101342
    - 101345
    - 101361
    - 101362
    - 101364
    - 101367
    - 101368
    - 101369
    - 101370
    - 101374
    - 101375
    - 101376
    - 101378
    - 101380
    - 101381
    - 101383
    - 101385
    - 101387
    - 101388
    - 101391
    - 101393
    - 101395
    - 101396
    - 101397
    - 130425
    - 130826
    - 130998
    - 131026
    - 131121
    - 131128
    - 131261
    - 131288
    - 131359
    - 131403
    - 131617
    - 131830
    - 131899
    - 131910
    - 131970
    - 133364
    - 133365
    - 133533
    - 133553
    - 133620
    - 133749
    - 133850
    - 134677
    - 134764
    - 134798
    - 135072
    - 135086
    - 135226
    - 135507
    - 135747
    - 136014
    - 136263
    - 136290
    - 136308
    - 136402
    - 136418
    - 136658
    - 136938
    - 137131
    - 137303
    - 137361
    - 137386
    - 137388
    - 137502
    - 137539
    - 137645
    - 138051
    - 138272
    - 138685
    - 139410
    - 139489
    - 139562
    - 139594
    - 139633
    - 139817
    - 140236
    - 140492
    - 140601
    - 142114
    - 142627
    - 142636
    - 142772
    - 143037
    - 143082
    - 143758
    - 143865
    - 144502
    - 144653
    - 144727
    - 144752
    - 144784
    - 145921
    - 145946
    - 146552
    - 146662
    - 146803
    - 147061
    - 147238
    - 147706
    - 148155
    - 148421
    - 148652
    - 149733
    - 150274
    - 150355
    - 150439
    - 150999
    - 151014
    - 151504
    - 152214

clinics:
  barnet:
    - name: Millway Medical Practice
      address_line_1: Hartley Ave
      address_town: London
      address_postcode: NW7 2HX
    - name: Chipping Barnet Library
      address_line_1: Stapylton Road
      address_town: High Barnet
      address_postcode: EN5 4QT
    - name: Oak Lodge Medical Practice
      address_line_1: 234 Burnt Oak Broadway
      address_town: Burnt Oak
      address_postcode: HA8 0AP
    - name: Ravenscroft Medical Practice
      address_line_1: Golders Green Rd
      address_town: London
      address_postcode: NW11 8BB
