organisation:
  ods_code: RYW

team:
  workgroup: birminghamsais
  name: Birmingham and Solihull Immunisation Team
  email: bchnt.birminghamimms@nhs.net
  phone: "01214663410"
  careplus_venue_code: UNKNOWN
  privacy_policy_url: https://www.bhamcommunity.nhs.uk/patient-privacy-notice/
  privacy_notice_url: https://www.bhamcommunity.nhs.uk/download.cfm?doc=docm93jijm4n6296.pdf&ver=11443
  reply_to_id: 57c9f60f-d430-4a47-9ef5-a7caf9ca7885
  type: poc_only

programmes: [flu, hpv, menacwy, mmr, td_ipv]

subteams:
  springfield:
    name: Springfield Team
    email: BCHNT.HPVTeamsouth@nhs.net
    phone: "01214663410"
    reply_to_id: 9dac769c-f5a8-4d42-a269-2421ad4ab953
  lansdowne:
    name: Lansdowne Team
    email: BCHNT.hpvteamcentral@nhs.net
    phone: "0121 245 5763"
    reply_to_id: 7f60d1e7-0601-491a-92ee-30d51635744d
  solihull:
    name: Solihull Team
    email: bchnt.solihullimms@nhs.net
    phone: "01214666545"
    reply_to_id: 70b686e7-b02d-41a6-ac45-70bbcf7422ce
  clinics:
    name: Birmingham and Solihull Immunisation Team (Clinics)
    email: bchnt.birminghamimms@nhs.net
    phone: "01214663410"

schools:
  springfield:
    - 130461
    - 148722
    - 142388
    - 134034
    - 145859
    - 146124
    - 140014
    - 137578
    - 135970
    - 141752
    - 139962
    - 136589
    - 103606
    - 143418
    - 103560
    - 141318
    - 141252
    - 133227
    - 148589
    - 103563
    - 143438
    - 103586
    - 103567
    - 134908
    - 139131
    - 139047
    - 103625
    - 131164
    - 137858
    - 144336
    - 136213
    - 136123
    - 147038
    - 137346
    - 144719
    - 146780
    - 139526
    - 134571
    - 141242
    - 147440
    - 137044
    - 137046
    - 103585
    - 150320
    - 148684
    - 136152
    - 103584
    - 134098
    - 103486
    - 136590
    - 103632
    - 103519
    - 145417
    - 136406
    - 103566
    - 103497
    - 139706
    - 139671
    - 142338
    - 103613
    - 103498
    - 135911
    - 138971
    - 144464
    - 103564
    - 135208
    - 141835
    - 151403
    - 142071
    - 140863
    - 144306
    - 148521
    - 103605
    - 103601
    - 139888
    - 103501
    - 139994
  lansdowne:
    - 144721
    - 149155
    - 103146
    - 145580
    - 136882
    - 138222
    - 137988
    - 140524
    - 143039
    - 149042
    - 103611
    - 139841
    - 103539
    - 148187
    - 137819
    - 138775
    - 141739
    - 141969
    - 143413
    - 136908
    - 135561
    - 143435
    - 138695
    - 139048
    - 139746
    - 135907
    - 103576
    - 103503
    - 103483
    - 103509
    - 137034
    - 141003
    - 137043
    - 143562
    - 138937
    - 137047
    - 145120
    - 136592
    - 148225
    - 148644
    - 143174
    - 138586
    - 136032
    - 151642
    - 137053
    - 103614
    - 148553
    - 146858
    - 134982
    - 147707
    - 103534
    - 103531
    - 138137
    - 136778
    - 138136
    - 103622
    - 150101
    - 139731
    - 138281
  solihull:
    - 149753
    - 135971
    - 136994
    - 136333
    - 103493
    - 141171
    - 149062
    - 145878
    - 147201
    - 104132
    - 129342
    - 131687
    - 104130
    - 136909
    - 136347
    - 103630
    - 137231
    - 137008
    - 142075
    - 104133
    - 104131
    - 138059
    - 141668
    - 143895
    - 143918
    - 104124
    - 134476
    - 147757
    - 135453
    - 104038
    - 146379
    - 136310
    - 142219

clinics:
  clinics:
    - name: Jaffray Resource Centre
      address_line_1: 7 Jaffray Crescent
      address_line_2: Erdington
      address_town: Birmingham
      address_postcode:
      ods_code: RYW42
    - name: Landsdowne Health Centre
      address_line_1: 34 Lansdowne Street
      address_line_2: Winson Green
      address_town: Birmingham
      address_postcode:
      ods_code: RYW44
    - name: Poplar Primary Care Centre
      address_line_1: 58 Poplar Road
      address_line_2: Kings Heath
      address_town: Birmingham
      address_postcode: B14 7AG
      ods_code: 5M152
    - name: Hall Green Health Centre
      address_line_1: 977-979 Stratford Rd
      address_town: Birmingham
      address_postcode:
      ods_code: 5M176
    - name: Solihull Methodist Church
      address_line_1: Solihull Methodist Church
      address_line_2: Blossomfield Rd
      address_town: Solihull
      address_postcode:
      ods_code:
    - name: Hobmoor Road Centre
      address_line_1: 192 Hob Moor road
      address_line_2: Small Heath
      address_town: Birmingham
      address_postcode:
      ods_code: RYW41
    - name: Castle Vale Primary Care Centre
      address_line_1: 70 Tangmere Drive
      address_line_2: Castle vale
      address_town: Birmingham
      address_postcode:
      ods_code: RYW30
    - name: Sutton Cottage Hospital
      address_line_1: 27a Birmingham Road
      address_line_2: Sutton Coldfield
      address_town: Birmingham
      address_postcode:
      ods_code: RYW20
    - name: St Margaret's Church Olton
      address_line_1: St Margaret's Rd
      address_line_2: Olton
      address_town: Solihull
      address_postcode:
      ods_code: SMCO
    - name: Solihull School
      address_line_1: 793 Warwick Road
      address_town: Solihull
      address_postcode:
      ods_code: EE104124
    - name: Saltley Health Centre
      address_line_1: 48 Cradock Rd
      address_line_2: Saltley
      address_town: Birmingham
      address_postcode:
      ods_code: RYW55
    - name: Riverside Lodge Intermediate Care Centre
      address_line_1: 160 Hobmoor Road
      address_line_2: Small Heath
      address_town: Birmingham
      address_postcode:
      ods_code: RYW13
    - name: Springfields Centre for Health Promotion
      address_line_1: Raddlebarn Road
      address_line_2: Selly Oak
      address_town: Birmingham
      address_postcode:
      ods_code: RYW60
    - name: West Heath Hospital
      address_line_1: Rednal Road
      address_line_2: West Heath
      address_town: Birmingham
      address_postcode:
      ods_code: RYW24
    - name: Quinton Lane Care Centre
      address_line_1: 27 Quinton Ln
      address_line_2: Quinton
      address_town: Birmingham
      address_postcode:
      ods_code: RYW53
    - name: Shirley Road Health Centre
      address_line_1: 189 Shirley Rd
      address_town: Birmingham
      address_postcode:
      ods_code: RYW57
