organisation:
  ods_code:

team:
  name:
  email:
  phone:
  careplus_venue_code:
  privacy_policy_url:

programmes: [flu, hpv, menacwy, mmr, td_ipv]

subteams:
  subteam1:
    name: XXX SMOKE TEST XXX
    email: xxx.smoke.test.xxx@example.nhs.net
    phone: "03003112233"

schools:
  subteam1:
    - XXXXXX

clinics:
  subteam1:
    - name: Test Clinic
      address_line_1: 1 Clinic Test Street
      address_town: Clinic Test Town
      address_postcode: TE1 1ST
      ods_code: XXXXX
