team:
  name: Coventry and Warwickshire Partnership NHS Trust
  email: example@covwarkpt.nhs.uk
  phone: 07700 900815
  ods_code: RYG
  careplus_venue_code: CWPTSI
  privacy_notice_url: https://www.covwarkpt.nhs.uk/download.cfm?ver=8286
  privacy_policy_url: https://www.covwarkpt.nhs.uk/privacy

programmes: [hpv]

subteams:
  generic:
    name: Coventry and Warwickshire Partnership NHS Trust
    email: example@covwarkpt.nhs.uk
    phone: 07700 900815

users:
  - email: nurse.ryg@example.com
    password: nurse.ryg@example.com
    given_name: Nurse
    family_name: RYG

schools:
  generic:
    - 141939
    - 103751
    - 103760
    - 139292
    - 134269
    - 150498
    - 141376
    - 140958
    - 149424
    - 131574
    - 141992
    - 146436
    - 137209
    - 136126
    - 103747
    - 142960
    - 140366
    - 135335
    - 141104
    - 137272
    - 147346
    - 103750
    - 142339
    - 137225
    - 140248
    - 138023
    - 140961
    - 134970
    - 141008
    - 125790
    - 149577
    - 137781
    - 136587
    - 140354
    - 145575
    - 125773
    - 145200
    - 140654
    - 137771
    - 125794
    - 140371
    - 138644
    - 137767
    - 143707
    - 145019
    - 149580
    - 141277
    - 148398
    - 139936
    - 139468
    - 134464
    - 144764
    - 142881
    - 136595
    - 125777
    - 141836
    - 125764
    - 136986
    - 137079
    - 148828
    - 136158
    - 136459
    - 139937
    - 148243
    - 148554
    - 137597
    - 149916
    - 145224
    - 137172
    - 136622
    - 125774
    - 137770
    - 147345
    - 145470
    - 137766
    - 125805
    - 136963
    - 136991
    - 146697
    - 147432
    - 137302
    - 125788
    - 148429
    - 136907
    - 142202
    - 136510
    - 125787
    - 138767
    - 143905
    - 143634
    - 137235
    - 137236
    - 136786
    - 125775
    - 148362
    - 144633
    - 148032
    - 125781
    - 145486

clinics:
  generic:
    - name: Jepson House
      address_line_1: 4 Manor Court Avenue
      address_town: Nuneaton
      address_postcode: CV11 5HX
    - name: Locke House
      address_line_1: The Railings Woodside Park
      address_town: Rugby
      address_postcode: CV21 2AW
    - name: Woodloes House
      address_line_1: Woodloes Avenue South
      address_town: Warwick
      address_postcode: CV34 5XN
    - name: Alcester Clinic
      address_line_1: Fields Park Drive
      address_town: Warwickshire
      address_postcode: B49 6QR
    - name: City Of Coventry Health Centre
      address_line_1: 2 Stoney Stanton Road
      address_town: Coventry
      address_postcode: CV1 4FS
