organisation:
  ods_code: AJC

team:
  workgroup: vaccsukdudleysais
  name: Vaccination UK - Dudley
  email: dudley@v-uk.co.uk
  phone: "0138 443 1712"
  careplus_venue_code: UNKNOWN
  privacy_policy_url: https://www.schoolvaccination.uk/privacy-policy
  privacy_notice_url: https://www.schoolvaccination.uk/privacy-policy
  reply_to_id: 40e0f4a7-b48b-43ed-ab2a-784bb3b8b118
  type: poc_only

programmes: [flu, hpv, td_ipv]

subteams:
  dudley:
    name: Vaccination UK - Dudley
    email: dudley@v-uk.co.uk
    phone: "0138 443 1712"
    reply_to_id: 40e0f4a7-b48b-43ed-ab2a-784bb3b8b118

schools:
  dudley:
    - 103869
    - 103806
    - 103818
    - 137705
    - 142047
    - 103828
    - 140126
    - 137571
    - 103792
    - 147708
    - 139437
    - 103776
    - 103777
    - 103819
    - 103778
    - 103801
    - 147479
    - 103838
    - 103835
    - 142964
    - 150053
    - 103810
    - 103846
    - 103790
    - 103781
    - 103829
    - 144078
    - 141570
    - 103876
    - 103786
    - 148182
    - 103822
    - 103832
    - 103799
    - 103881
    - 103847
    - 143822
    - 103820
    - 143196
    - 103814
    - 103802
    - 103807
    - 143537
    - 141560
    - 103845
    - 144080
    - 137773
    - 143782
    - urn: 143582
      site: "A"
      name: "Leasowes High School (Main Site)"
    - urn: 143582
      site: "B"
      name: "Leasowes High School (Additional Site)"
    - 143783
    - 103779
    - 142355
    - 103834
    - 103780
    - 144079
    - 144418
    - 103815
    - 147155
    - 103870
    - 103839
    - 144301
    - 103850
    - 103848
    - 137390
    - 103883
    - 103791
    - 148642
    - 145305
    - 103830
    - 103826
    - 103784
    - 139872
    - 141712
    - 103821
    - 103882
    - 148685
    - 103813
    - 144081
    - 140144
    - 144657
    - 103851
    - 140147
    - 141477
    - 103840
    - 103836
    - 103837
    - 141489
    - 103827
    - 103854
    - 103877
    - 134768
    - 143195
    - urn: 151763
      site: "A"
      name: "The Brier School (Main Site)"
    - urn: 151763
      site: "B"
      name: "The Brier School (Additional Site)"
    - 141979
    - 141325
    - 103855
    - 137812
    - 144952
    - 103880
    - 145593
    - 103805
    - 144374
    - 145563
    - 103858
    - 143818
    - 103787
    - 147721
    - 136618
    - 103809
    - 103800
    - 103879
    - 143821
    - 103823
    - 150921



clinics:
  dudley:
    - name: Oakfield Community Centre
      address_line_1: 245 Brettal Lane
      address_town: Brierley Hill
      address_postcode: DY5 3LT
