organisation:
  ods_code: G6R5B

team:
  workgroup: vaccsukenfieldsais
  name: Vaccination UK - Enfield
  email: enfield@v-uk.co.uk
  phone: "0208 150 7505"
  careplus_venue_code: UNKNOWN
  privacy_policy_url: https://www.schoolvaccination.uk/policies
  privacy_notice_url: https://www.schoolvaccination.uk/policies
  reply_to_id: 1db6b63c-cdc3-47d5-abc4-3d7297ab20a1
  type: point_of_care

programmes: [menacwy, mmr, td_ipv, hpv]

subteams:
  enfield:
    name: Vaccination UK - Enfield
    email: enfield@v-uk.co.uk
    phone: "0208 150 7505"
    reply_to_id: 1db6b63c-cdc3-47d5-abc4-3d7297ab20a1

# 134580 closed with no successor
schools:
  enfield:
    - 101972
    - 101981
    - 101983
    - 101984
    - 101989
    - 101992
    - 101993
    - 101994
    - 101996
    - 101997
    - 102002
    - 102003
    - 102004
    - 102005
    - 102006
    - 102014
    - 102024
    - 102026
    - 102027
    - 102028
    - 102029
    - 102030
    - 102031
    - 102032
    - 102033
    - 102034
    - 102035
    - 102036
    - 102037
    - 102038
    - 102039
    - 102040
    - 102041
    - 102045
    - 102048
    - 102049
    - 102052
    - 102053
    - 102054
    - 102055
    - 102056
    - 102058
    - 102060
    - 102061
    - 102062
    - 102063
    - 102064
    - 102065
    - 102066
    - 102067
    - 102069
    - 102070
    - 130438
    - 130958
    - 131407
    - 131657
    - 132203
    - 132256
    - 134307
    - 134311
    - 135839
    - 135958
    - 136147
    - 136327
    - 136952
    - 137094
    - 138203
    - 138381
    - 139599
    - 139815
    - 141017
    - 141247
    - 142727
    - 142874
    - 143036
    - 143197
    - 143198
    - 143199
    - 143200
    - 143201
    - 143202
    - 143924
    - 144084
    - 145201
    - 145207
    - 145232
    - 145522
    - 145955
    - 145968
    - 145984
    - 145985
    - 145986
    - 146663
    - 146728
    - 146862
    - 146868
    - 146882
    - 146900
    - 146935
    - 146946
    - 147536
    - 148358
    - 149100
    - 150114
    - 150663
    - 151401
    - 151543
    - 152093

clinics:
  enfield:
    - name: Evergreen Surgery
      address_line_1: 1 Smythe Close
      address_town: London
      address_postcode: N9 0TW
    - name: The Ordnance Unity Centre For Health
      address_line_1: 645 Hertford Rd
      address_town: Enfield
      address_postcode: EN3 6ND
    - name: Carlton House Surgery
      address_line_1: 28 Tenniswood Rd
      address_town: Enfield
      address_postcode: EN1 3LL
