organisation:
  ods_code: AJC

team:
  workgroup: vaccsukhaveringsais
  name: Vaccination UK - Havering
  email: havering@v-uk.co.uk
  phone: "0203 343 2400"
  careplus_venue_code: UNKNOWN
  privacy_policy_url: https://www.schoolvaccination.uk/policies
  privacy_notice_url: https://www.schoolvaccination.uk/policies
  reply_to_id: 4f32222d-aefb-4802-820a-f447817c3550
  type: poc_only

programmes: [hpv, menacwy, td_ipv, flu]

subteams:
  havering:
    name: Vaccination UK - Havering
    email: havering@v-uk.co.uk
    phone: "0203 343 2400"
    reply_to_id: 4f32222d-aefb-4802-820a-f447817c3550

schools:
  havering:
    - 145510
    - 138326
    - 145192
    - 144094
    - 102360
    - 139307
    - 137414
    - 137040
    - 143130
    - 143946
    - 136663
    - 146309
    - 136576
    - 102362
    - 143428
    - 137197
    - 137233
    - 136600
    - 144095
    - 143877
    - 137396
    - 146973
    - 142722
    - 136090
    - 142050
    - 149720
    - 145944
    - 102276
    - 102328
    - 102335
    - 102299
    - 141299
    - 141173
    - 102309
    - 102313
    - 149452
    - 149451
    - 102321
    - 102280
    - 139406
    - 145111
    - 143216
    - 102329
    - 102336
    - 131590
    - 102272
    - 146136
    - 102283
    - 102316
    - 144596
    - 102285
    - 144589
    - 144590
    - 102319
    - 102330
    - 102324
    - 102312
    - 102314
    - 132766
    - 135588
    - 102334
    - 102361
    - 138943
    - 138944
    - 102268
    - 102308
    - 102355
    - 102303
    - 102357
    - 102278
    - 102269
    - 102325
    - 102332
    - 102317
    - 142966
    - 140818
    - 102322
    - 141577
    - 141549
    - 146185
    - 102331
    - 140022
    - 102291
    - 142885
    - 131426
    - 102295
    - 102294
    - 135812

clinics:
  havering:
    - name: St Edward The Confessor
      address_line_1: Market Place
      address_town: Romford
      address_postcode: RM1 3AB
      ods_code:
    - name: Royals Youth Centre
      address_line_1: Viking Way
      address_town: Rainham
      address_postcode: RM13 9YG
      ods_code:
    - name: MyPlace Youth & Community Centre
      address_line_1: 343 Dagnam Park Drive
      address_town: Romford
      address_postcode: RM3 9EN
      ods_code:
    - name: Fairkytes Art Centre
      address_line_1: 51-53 Billet Lane
      address_town: Hornchurch
      address_postcode: RM11 1AX
      ods_code:
