organisation:
  name: Hertfordshire and East Anglia Community School Age Immunisation Service
  email: hct.csaisherts@nhs.net
  phone: 0300 555 5055
  ods_code: RY4
  careplus_venue_code: UNUSED
  privacy_notice_url: https://www.hct.nhs.uk/privacy
  privacy_policy_url: https://www.hct.nhs.uk/privacy

programmes: [hpv]

subteams:
  cambridgeshire-and-peterborough:
    name: Cambridgeshire and Peterborough Community and School Age Immunisation Service
    email: hct.csaiscambspb@nhs.net
    phone: 0300 555 5055
  essex:
    name: Hertfordshire Community School Age Immunisation Service
    email: hct.csaisherts@nhs.net
    phone: 0300 555 5055

users:
  - email: nurse.ry4@example.com
    password: nurse.ry4@example.com
    given_name: Nurse
    family_name: RY4

schools:
  cambridgeshire-and-peterborough:
    - 110907
    - 135263
    - 136023
    - 136266
    - 136398
    - 136580
    - 137082
    - 139082
    - 142902
    - 145051
    - 145271
  essex:
    - 115237
    - 115239
    - 115322
    - 115382
    - 115386
    - 115387
    - 115395
    - 115396
    - 115399
    - 115402
    - 115425
    - 115429
    - 115457
    - 115466
    - 135651
    - 135837
    - 135837
    - 135837
    - 136342
    - 136443
    - 136444
    - 136490
    - 136555
    - 136579
    - 136605
    - 136625
    - 136642
    - 136776
    - 136861
    - 136868
    - 137072
    - 137152
    - 137214
    - 137240
    - 137260
    - 137310
    - 137312
    - 137445
    - 137552
    - 137554
    - 137727
    - 137733
    - 137874
    - 137926
    - 137927
    - 137937
    - 137944
    - 137945
    - 137975
    - 138044
    - 138174
    - 138219
    - 138734
    - 138736
    - 138865
    - 139153
    - 139179
    - 139248
    - 139402
    - 139534
    - 139578
    - 140861
    - 141741
    - 141765
    - 141765
    - 141841
    - 141945
    - 141947
    - 142612
    - 142938
    - 142940
    - 143144
    - 143589
    - 143590
    - 143639
    - 143701
    - 144691
    - 144692
    - 144897
    - 144956
    - 145061
    - 145597
    - 145916
    - 145987
    - 146601
    - 146795
    - 147031
    - 147080
    - 147537
    - 147815
    - 148422
    - 148539
    - 148543
    - 149112
    - 151442

clinics:
  cambridgeshire-and-peterborough:
    - name: North Cambridgeshire Hospital
      address_line_1: Churchill Road
      address_town: Wisbech
      address_postcode: PE13 3AB
