organisation:
  ods_code: AJC

team:
  workgroup: vaccsukhillingdonsais
  name: Vaccination UK - Hillingdon
  email: hillingdon@v-uk.co.uk
  phone: 020 8150 1220
  careplus_venue_code: UNKNOWN
  privacy_policy_url: https://www.schoolvaccination.uk/privacy-policy
  privacy_notice_url: https://www.schoolvaccination.uk/policies
  reply_to_id:
  type: point_of_care

programmes:
  - menacwy
  - mmr
  - td_ipv
  - hpv

subteams:
  hillingdon:
    name: Vaccination UK - Hillingdon
    email: hillingdon@v-uk.co.uk
    phone: 020 8150 1220
    reply_to_id:

# I've decided against creating sites as addresses were not provided
schools:
  hillingdon:
    - 102458
    - 137844
    - 138983
    - 137407
    - 102417
    - 137633
    - 102422
    - 102368
    - 139117
    - 139609
    - 131638
    - 102373
    - urn: 151478
      site: B
      name: Hillingdon Manor Primary School (Yiewsley Grange) sattelite site
      address_line_1: ""
      address_postcode: UB7 7QP
    - 102375
    - 139295
    - 139306
    - 138613
    - 141035
    - 102377
    - 102379
    - 148774
    - 102414
    - 102380
    - 142887
    - 102432
    - 102432
    - 152152
    - 152151
    - 136329
    - 102382
    - 102381
    - 135004
    - 102451
    - 102383
    - 102384
    - 136519
    - 102439
    - 102385
    - 102465
    - 148775
    - 137078
    - 139909
    - 102407
    - urn: 151478
      site: C
      name: Colne Grange (part of Upton Grange Dachet Slough Imms)
      address_line_1: ""
      address_postcode: UB8 2YG
    - 131940
    - 141055
    - 102434
    - 102435
    - 102418
    - 140387
    - 102388
    - 136046
    - 140391
    - 139275
    - 102462
    - 102392
    - 102391
    - 138158
    - 139926
    - 102394
    - 102393
    - 102452
    - 137829
    - 102430
    - 102449
    - 145121
    - 138368
    - 141606
    - 102464
    - 140671
    - 136711
    - 102408
    - 137077
    - 141561
    - 102416
    - 140748
    - 141718
    - 102426
    - 102438
    - 151809
    - 102424
    - 102456
    - 102453
    - 102457
    - 140484
    - 102454
    - 102425
    - 139302
    - 102421
    - 136631
    - 102369
    - 137925
    - 101964
    - 143714
    - 149033
    - 137652
    - 146375
    - 136768
    - 137635
    - 102409
    - 145041
    - 102411
    - 102399
    - 102413
    - 102400
    - 144473
    - 138621
    - 102404
    - 102403

clinics:
  hillingdon:
    - name: Stockley Park Community Clinic
      address_line_1: 6 â€“ 9 The Square
      address_line_2: Stockley Park
      address_town: Uxbridge
      address_postcode: UB11 1FW
