organisation:
  ods_code: AJC

team:
  workgroup: vaccsukhullandeastridingsais
  name: Vaccination UK - Hull & East Riding
  email: hullandeastriding@v-uk.co.uk
  phone: "01482 453690"
  careplus_venue_code: UNKNOWN
  privacy_policy_url: https://www.schoolvaccination.uk/policies
  privacy_notice_url: https://www.schoolvaccination.uk/policies
  reply_to_id: 8d4721f4-e5db-49db-8eb4-86fd37990391
  type: poc_only

programmes: [menacwy, mmr, td_ipv, hpv]

subteams:
  hullandeastriding:
    name: Vaccination UK - Hull & East Riding
    email: hullandeastriding@v-uk.co.uk
    phone: "01482 453690"
    reply_to_id: 8d4721f4-e5db-49db-8eb4-86fd37990391

#Checking URN 117719...
#  ✗ Closed: Closed
#    → Successor: 147270
#
#Checking URN 117720...
#  ✗ Closed: Closed
#    → Successor: 147259
#
#Checking URN 118117...
#  ✗ Closed: Closed
#    → Successor: 144104
#
#Checking URN 118141...
#  ✗ Closed: Closed
#    → Successor: 139628
#
#Checking URN 133480...
#  ✗ Closed: Closed
#    → Successor: 151519
#
#Checking URN 117971...
#  ✗ Closed: Closed
#    → Successor: 150840
#
#Checking URN 117829...
#  ✗ Closed: Closed
#    → Successor: 149259
#
#Checking URN 117851...
#  ✗ Closed: Closed
#    → Successor: 151160
#
#Checking URN 118127...
#  ✗ Closed: Closed
#    → Successor: None
#
#Checking URN 118121...
#  ✗ Closed: Closed
#    → Successor: 149974
#
#Checking URN 117854...
#  ✗ Closed: Closed
#    → Successor: 149260
#
#Checking URN 117886...
#  ✗ Closed: Closed
#    → Successor: 151530
#
#Checking URN 137307...
#  ✗ Closed: Closed
#    → Successor: 137306
#
#Checking URN 142135...
#  ✗ Closed: Closed
#    → Successor: 150256
#Checking URN 147270...
##  ✗ Closed: Closed
##    → Successor: 147259
##
schools:
  hullandeastriding:
    - 144672
    - 139570
    - 144421
    - 140229
    - 139838
    - 139508
    - 140235
    - 144669
    - 140847
    - 139511
    - 143225
    - 140902
    - 140437
    - 144677
    - 139848
    - 140169
    - 139525
    - 139850
    - 140184
    - 140905
    - 140716
    - 141078
    - 118123
    - 147259
    - 144605
    - 138679
    - 139512
    - 141037
    - 143224
    - 140275
    - 140245
    - 144671
    - 140246
    - 139921
    - 144583
    - 140247
    - 138677
    - 141719
    - 147628
    - 144305
    - 144670
    - 142440
    - 142260
    - 140290
    - 145611
    - 145431
    - 140849
    - 140587
    - 118051
    - 144102
    - 144103
    - 143226
    - 141387
    - 140903
    - 140906
    - 141649
    - 144101
    - 140848
    - 143223
    - 141720
    - 145612
    - 139513
    - 144674
    - 138678
    - 139922
    - 139886
    - 142307
    - 144673
    - 139799
    - 140830
    - 139579
    - 139968
    - 144676
    - 148588
    - 146220
    - 140904
    - 118131
    - 135598
    - 118183
    - 118140
    - 130579
    - 138082
    - 144422
    - 143221
    - 139118
    - 142150
    - 144307
    - 144766
    - 138246
    - 135945
    - 144104
    - 139395
    - 143222
    - 142391
    - 139629
    - 139628
    - 117888
    - 145596
    - 117823
    - 147408
    - 147407
    - 132349
    - 117875
    - 117824
    - 118122
    - 151519
    - 117969
    - 117825
    - 117970
    - 150840
    - 149259
    - 117972
    - 117941
    - 117830
    - 117831
    - 117842
    - 117878
    - 118000
    - 117833
    - 117832
    - 117838
    - 117973
    - 117839
    - 118002
    - 118025
    - 145177
    - 117974
    - 117840
    - 140119
    - 145189
    - 117841
    - 117891
    - 117976
    - 117977
    - 144471
    - 135078
    - 151160
    - 135700
    - 117852
    - 145595
    - 133519
    - 117853
    - 149974
    - 149260
    - 142119
    - 117855
    - 117911
    - 133481
    - 147760
    - 117980
    - 117936
    - 117872
    - 117981
    - 117990
    - 118001
    - 117912
    - 117937
    - 151530
    - 146161
    - 117983
    - 117889
    - 117982
    - 117858
    - 117909
    - 117859
    - 117860
    - 147504
    - 117985
    - 117861
    - 117916
    - 147210
    - 117935
    - 145190
    - 117862
    - 137306
    - 117987
    - 143587
    - 118044
    - 117864
    - 140551
    - 117893
    - 117892
    - 117939
    - 146174
    - 117989
    - 143823
    - 117992
    - 117882
    - 117993
    - 118028
    - 117894
    - 118003
    - 117885
    - 144082
    - 117881
    - 147252
    - 148164
    - 118034
    - 147248
    - 118030
    - 147244
    - 149622
    - 143586
    - 118026
    - 137151
    - 117942
    - 132209
    - 135077
    - 117995
    - 117866
    - 117996
    - 117867
    - 117868
    - 117883
    - 117997
    - 149646
    - 135115
    - 141933
    - 118120
    - 117999
    - 133429
    - 137306
    - 118144
    - 136995
    - 118072
    - 118111
    - 136921
    - 143854
    - 118132
    - 145929
    - 118085
    - 145722
    - 118082
    - 146129
    - 118073
    - 118148
    - 118145
    - 148767
    - 136667
    - 118076
    - 140866
    - 150256
    - 118126
    - 118075
    - 143588
    - 144561

clinics:
  hullandeastriding:
    - name: The Deep Business Centre
      address_line_1: Tower Street
      address_town:
      address_postcode: HU1 4BG
    - name: Freedom Centre
      address_line_1: 97 Preston Road
      address_town:
      address_postcode: HU9 3QB
    - name: Priory Children's Centre
      address_line_1: Priory Road
      address_town:
      address_postcode: HU5 5RU
    - name: Lemon Tree
      address_line_1: 2 Lothian Way
      address_town:
      address_postcode: HU7 5DD
