organisation:
  name: Leicestershire Partnership Trust School Aged Immunisation Service
  email: lpt.sais@nhs.net
  phone: 0300 3000 007
  ods_code: RT5YA
  careplus_venue_code: UNUSED
  privacy_notice_url: https://www.leicspart.nhs.uk/privacy-policy/
  privacy_policy_url: https://www.leicspart.nhs.uk/privacy-policy/
  reply_to_id: 53938717-b6ce-4b08-9304-ad8c763a6189

programmes: [hpv]

teams:
  generic:
    name: Leicestershire Partnership Trust School Aged Immunisation Service
    email: lpt.sais@nhs.net
    phone: 0300 3000 007
    reply_to_id: 53938717-b6ce-4b08-9304-ad8c763a6189

schools:
  generic:
    - 141916
    - 137931
    - 148546
    - 137115
    - 138721
    - 120277
    - 138108
    - 146108
    - 147068
    - 138628
    - 140103

clinics:
  generic:
    - name: Leicestershire Partnership Trust SAIS Clinic
