organisation:
  ods_code: I4K0Y

team:
  workgroup: vaccsuklincssais
  name: Vaccination UK - North & North East Lincolnshire
  email: lincs@v-uk.co.uk
  phone: "01724 514800"
  careplus_venue_code: UNKNOWN
  privacy_policy_url: https://www.schoolvaccination.uk/policies
  privacy_notice_url: https://www.schoolvaccination.uk/policies
  reply_to_id: 69f157fa-c166-47c2-94e3-adb0ae88dd6e
  type: poc_only

programmes: [menacwy, mmr, td_ipv, hpv]

subteams:
  lincs:
    name: Vaccination UK - North & North East Lincolnshire
    email: lincs@v-uk.co.uk
    phone: "01724 514800"
    reply_to_id: 69f157fa-c166-47c2-94e3-adb0ae88dd6e

# Replaced the following schools with their successors
#  117725 → 151798
#  117729 → 150025
#  117730 → 151799
#  118011 → 151079
#  137832 → 150867
#  117739 → 151800
#  118037 → 151081
#  118018 → 151080
#  118021 → 148307
#  118012 → 149973
#  117956 → 150965
#  118015 → 150519
schools:
  lincs:
    - 145462
    - 151798
    - 117726
    - 118006
    - 118109
    - 118007
    - 117781
    - 117780
    - 117727
    - 117812
    - 117728
    - 150025
    - 151799
    - 117747
    - 117967
    - 141485
    - 117934
    - 139035
    - 135247
    - 117736
    - 118043
    - 117768
    - 142130
    - 138712
    - 134589
    - 118097
    - 117748
    - 117737
    - 118010
    - 151079
    - 138085
    - 117811
    - 150867
    - 118005
    - 117743
    - 118014
    - 151800
    - 117771
    - 133700
    - 117740
    - 139059
    - 117741
    - 118023
    - 134867
    - 139024
    - 139025
    - 139277
    - 137004
    - 146267
    - 150449
    - 117756
    - 149400
    - 149592
    - 138017
    - 138827
    - 138086
    - 118016
    - 118112
    - 137742
    - 117752
    - 135065
    - 118004
    - 138018
    - 138016
    - 118146
    - 118147
    - 151081
    - 138015
    - 136058
    - 137759
    - 140626
    - 135674
    - 137453
    - 140343
    - 151080
    - 131216
    - 138713
    - 140625
    - 117753
    - 118020
    - 138831
    - 117787
    - 118038
    - 138520
    - 148307
    - 118022
    - 151702
    - 151703
    - 139649
    - 142828
    - 138467
    - 140991
    - 136192
    - 149511
    - 137811
    - 139981
    - 138857
    - 141773
    - 142269
    - 141631
    - 131231
    - 142841
    - 135294
    - 141302
    - 136277
    - 137200
    - 149973
    - 140801
    - 137394
    - 137464
    - 140581
    - 147462
    - 137611
    - 142969
    - 138890
    - 137996
    - 137761
    - 135176
    - 138237
    - 135209
    - 139472
    - 137196
    - 138846
    - 141101
    - 144148
    - 117733
    - 139952
    - 139009
    - 150965
    - 137787
    - 141585
    - 136975
    - 138062
    - 142268
    - 118124
    - 138014
    - 118125
    - 143281
    - 118017
    - 150519
    - 138866
    - 130585
    - 137363
    - 144366
    - 138468
    - 137760
    - 136268
    - 138279
    - 141289
    - 117926
    - 143884
    - 139420
    - 146762
    - 138975
    - 138542

clinics:
  lincs:
    - name: Normanby Gateway
      address_line_1: Lysagths Way
      address_town: Scunthorpe
      address_postcode: DN15 9YG
    - name: Grimsby Town Hall
      address_line_1: Town Hall Square
      address_town: Grimsby
      address_postcode: DN31 9ZZ
    - name: Immingham Family Hub
      address_line_1: Margaret Street
      address_town: Immingham
      address_postcode: DN40 1LD
    - name: Open Door
      address_line_1: Albion Street
      address_town:
      address_postcode: DN32 7DL
    - name: Scunthrope Library
      address_line_1: Carlton Street
      address_town:
      address_postcode: DN15 6TX
