organisation:
  ods_code: RW4

team:
  workgroup: mcnsais
  name: Mersey Care
  email: mcn-tr.schoolimmunisations@nhs.net
  phone: 0151 351 8805
  careplus_venue_code: UNKNOWN
  privacy_policy_url: https://www.merseycare.nhs.uk/about-us/privacy
  privacy_notice_url: https://www.merseycare.nhs.uk/about-us/privacy/privacy-statement
  reply_to_id: null
  type: point_of_care

programmes:
  - menacwy
  - mmr
  - td_ipv
  - hpv

subteams:
  knowsleyhaltonandsthelen:
    name: Mersey Care - Knowsley, Halton & St Helens Schools
    email: mcn-tr.schoolimmunisations@nhs.net
    phone: 0151 351 8805
    reply_to_id:
  liverpool:
    name: Mersey Care - Liverpool
    email: mcn-tr.vacandimms.team@nhs.net
    phone: 0151 295 3833
    reply_to_id:
  sefton:
    name: Mersey Care - Sefton
    email: mcn-tr.seftonimmunisationteam@nhs.net
    phone: 0151 247 6130
    reply_to_id:
  clinics:
    name: Mersey Care - Clinics
    email: mcn-tr.schoolimmunisations@nhs.net
    phone: 0151 351 8805
    reply_to_id:

schools:
  knowsleyhaltonandsthelen:
    - 104757
    - 132033
    - 132033
    - 104757
    - 148840
    - 135479
    - 131217
    - 104758
    - 104498
    - 148797
    - 111515
    - 104771
    - 111217
    - 111175
    - 150556
    - 144355
    - 104773
    - 149032
    - 104495
    - 140612
    - 130259
    - 146110
    - 132195
    - 134661
    - 111116
    - 111514
    - 104814
    - 104829
    - 143456
    - 143602
    - 150833
    - 147266
    - 104447
    - 104770
    - 104788
    - 104783
    - 104446
    - 111197
    - 111394
    - 141033
    - 104778
    - 111176
    - 104774
    - 111294
    - 111244
    - 139614
    - 143457
    - 150963
    - 144105
    - 149959
    - 104818
    - 111169
    - 104804
    - 104454
    - 104468
    - 132188
    - 136421
    - 138597
    - 135796
    - 145435
    - 147267
    - 104448
    - 140001
    - 104500
    - 141205
    - 104423
    - 134865
    - 129571
    - 104782
    - 104777
    - 140412
    - 111199
    - 104776
    - 104427
    - 104418
    - 104784
    - 131022
    - 104432
    - 110990
    - 111188
    - 111174
    - 104775
    - 135807
    - 146120
    - 151020
    - 133322
    - 136185
    - 140864
    - 111378
    - 133320
    - 104459
    - 148522
    - 143768
    - 145458
    - 104429
    - 142552
    - 111141
    - 149817
    - 149567
    - 151259
    - 104839
    - 130382
    - 149929
    - 148365
    - 144327
    - 144326
    - 104444
    - 104797
    - 104761
    - 104762
    - 104420
    - 111314
    - 148534
    - 111457
    - 104479
    - 147683
    - 104769
    - 104463
    - 104798
    - 104467
    - 131332
    - 104470
    - 104477
    - 104805
    - 142154
    - 149031
    - 141980
    - 104806
    - 104815
    - 111390
    - 111372
    - 111371
    - 151844
    - 104474
    - 111320
    - 104480
    - 111319
    - 147253
    - 111391
    - 146429
    - 104476
    - 111392
    - 104812
    - 131836
    - 104472
    - 104819
    - 104461
    - 104475
    - 104460
    - 104481
    - 104466
    - 104469
    - 111380
    - 142161
    - 104453
    - 150505
    - 150302
    - 104813
    - 150879
    - 104464
    - 147262
    - 111393
    - 104810
    - 104801
    - 104807
    - 104823
    - 104809
    - 104835
    - 104802
    - 136222
    - 104764
    - 104791
    - 143878
    - 104763
    - 134321
    - 111124
    - 140578
    - 149654
    - 144617
    - 136779
    - 111321
    - 142798
    - 150794
    - 136141
    - 104837
    - 110992
    - 139368
    - 104787
    - 134888
    - 111240
    - 135749
    - 150204
    - 111114
    - 104431
    - 145613
    - 141538
    - 104843
    - 146848
    - 150877
    - 111177
    - 111125
    - 146115
  liverpool:
    - 133441
    - 133441
    - 133441
    - 150210
    - 150210
    - 141103
    - 141103
    - 139686
    - 139686
    - 104751
    - 104751
    - 135656
    - 135656
    - 135656
    - 104748
    - 104748
    - 150535
    - 150535
    - 150149
    - 150149
    - 104736
    - 104507
    - 144493
    - 136119
    - 134250
    - 148226
    - 140975
    - 104717
    - 152034
    - 135267
    - 132119
    - 104516
    - 104517
    - 104519
    - 138183
    - 104729
    - 135174
    - 145182
    - 145438
    - 150202
    - 104521
    - 141076
    - 137916
    - 133691
    - 104593
    - 104522
    - 133335
    - 104611
    - 104713
    - 104698
    - 104714
    - 104723
    - 148199
    - 104503
    - 134658
    - 152033
    - 138787
    - 134210
    - 104629
    - 104730
    - 104742
    - 104530
    - 146768
    - 148792
    - 149530
    - 148655
    - 130296
    - 141960
    - 104504
    - 104506
    - 131105
    - 145463
    - 138379
    - 104505
    - 149406
    - 131818
    - 133336
    - 150131
    - 145735
    - 150956
    - 133332
    - 104610
    - 139114
    - 141330
    - 104688
    - 106433
    - 136062
    - 104634
    - 104635
    - 133421
    - 104549
    - 136118
    - 104703
    - 104682
    - 137675
    - 131800
    - 152038
    - 150850
    - 133262
    - 130395
    - 133333
    - 104555
    - 104554
    - 139588
    - 133309
    - 133334
    - 131480
    - 104557
    - 104591
    - 133331
    - 104636
    - 148471
    - 145359
    - 148620
    - 104600
    - 131065
    - 104564
    - 151314
    - 150373
    - 131837
    - 104632
    - 104638
    - 104670
    - 133337
    - 104642
    - 133702
    - 134471
    - 104569
    - 104750
    - 143912
    - 147665
    - 104571
    - 104749
    - 141937
    - 145360
    - 104735
    - 147178
    - 148172
    - 104641
    - 130961
    - 131597
    - 104545
    - 149133
    - 104622
    - 104681
    - 104676
    - 104643
    - 151673
    - 133615
    - 104648
    - 150244
    - 104649
    - 136735
    - 104640
    - 104651
    - 104650
    - 150713
    - 104678
    - 104721
    - 104652
    - 104715
    - 132796
    - 104712
    - 134245
    - 138850
    - 104624
    - 132793
    - 133330
    - 104656
    - 149132
    - 142523
    - 104679
    - 104660
    - 104673
    - 104661
    - 104664
    - 141582
    - 150351
    - 104667
    - 104734
    - 133338
    - 139589
    - 145086
    - 151857
    - 149134
    - 104616
    - 133329
    - 138696
    - 104570
    - 104589
    - 104739
    - 136813
  sefton:
    - 150079
    - 150557
    - 104868
    - 132208
    - 149829
    - 137297
    - 104860
    - 104942
    - 137514
    - 104893
    - 104964
    - 146688
    - 104980
    - 137533
    - 148931
    - 151208
    - 104931
    - 104863
    - 104862
    - 150813
    - 150658
    - 137436
    - 151376
    - 104883
    - 104926
    - 104884
    - 137604
    - 104878
    - 141693
    - 104962
    - 104915
    - 104940
    - 149029
    - 145454
    - 104869
    - 104850
    - 146895
    - 150852
    - 138260
    - 104886
    - 104887
    - 104853
    - 151390
    - 141694
    - 146187
    - 104891
    - 137520
    - 104960
    - 104866
    - 104889
    - 149828
    - 104973
    - 152092
    - 104856
    - 104982
    - 104879
    - 104865
    - 136088
    - 104930
    - 151021
    - 151111
    - 104935
    - 104929
    - 152154
    - 133748
    - 104977
    - 137612
    - 104885
    - 134371
    - 150660
    - 149047
    - 149377
    - 146313
    - 134343
    - 145453
    - 135085
    - 151023
    - 104932
    - 104925
    - 104936
    - 104938
    - 104941
    - 104894
    - 104920
    - 104897
    - 104921
    - 151022
    - 151777
    - 104905
    - 104922
    - 104900
    - 104918
    - 104898
    - 104902
    - 104906
    - 145096
    - 104934
    - 104972
    - 144618
    - 104882
    - 150851
    - 151569
    - 149486
    - 150834
    - 150762
    - 151292
    - 104937
    - 150659
    - 150657
    - 104881

clinics:
  clinics:
    - name: Halewood Health Centre
      address_line_1: Roseheath Avenue
      address_town: Halewood
      address_postcode: L26 9UH
      ods_code: H8F4D
    - name: St Chads Clinic
      address_line_1: St Chads Drive
      address_town: Kirkby
      address_postcode: L32 8RE
      ods_code: P4W6C
    - name: Manor Farm Clinic
      address_line_1: Manor Farm Road
      address_town: Huyton
      address_postcode: L36 0UB
      ods_code: T7B0C
    - name: Whiston Primary Care Resource Centre
      address_line_1: Old Colliery Road
      address_town: Whiston
      address_postcode: L35 3SX
      ods_code: X0T8F
    - name: Prescot Primary Care Resource Centre
      address_line_1: Sewell Street
      address_town: Prescot
      address_postcode: L34 1ND
      ods_code: J0E6R
    - name: North Huyton Primary Care Resource Centre
      address_line_1: Woolfall Heath Avenue
      address_town: Huyton
      address_postcode: L36 3TN
      ods_code: Q7N6D
    - name: Childwall Fiveways Health Centre
      address_line_1: 125 Childwall Road
      address_town: Wavertree
      address_postcode: L15 6US
      ods_code: RW45C
    - name: Mere Lane Health Centre
      address_line_1: 51 Mere Lane
      address_town: Liverpool
      address_postcode: L6 0QW
      ods_code: null
    - name: South Liverpool NHS Treatment Centre
      address_line_1: 32 Church Road
      address_town: Garston
      address_postcode: L19 2LW
      ods_code: RW44V
    - name: Townsend Lane Neighbourhood Health Centre
      address_line_1: 98 Townsend Lane
      address_postcode: L6 0AY
      ods_code: RW44W
    - name: Prince Street Clinic
      address_line_1: Prince Street
      address_town: Waterloo
      address_postcode: L22 5PB
      ods_code: RW42J
    - name: Litherland Town Hall Health Centre
      address_line_1: Hatton Hill Road
      address_town: Liverpool
      address_postcode: L21 9JN
      ods_code: RW42H
    - name: Southport Centre For Health and Wellbeing
      address_line_1: 44-46 Hoghton Street
      address_town: Southport
      address_postcode: PR9 0PQ
      ods_code: U0F9V
    - name: Maghull Health Centre
      address_line_1: Westway
      address_town: Maghull
      address_postcode: L31 0DJ
      ods_code: RW42G
    - name: Ainsdale Centre for Health and Wellbeing
      address_line_1: 164 Sanbrook Road
      address_town: Southport
      address_postcode: PR8 3RJ
      ods_code: B8O5Z
    - name: Ashtons Green Children's Centre
      address_line_1: Ashtons Green Drive
      address_postcode: WA9 2AP
      ods_code: J7Y5C
    - name: Kensington Neigbourhood Health Centre
      address_line_1: 155-157 Edge Lane
      address_town: Liverpool
      address_postcode: L7 2PF
      ods_code: RW44X
    - name: Princes Park Health Centre
      address_line_1: 9 Bentley Road
      address_postcode: L8 0SY
      ods_code: RW43Q
    - name: The Bridges Learning Centre
      address_line_1: Crow Wood Health Park, Crow Wood Lane
      address_postcode: WA8 3LZ
      ods_code: D9H6X
    - name: Vine street Resource Centre
      address_line_1: 30A Widnes Road
      address_postcode: WA8 6AD
      ods_code: E5U5O
    - name: Widnes Health Care Resource Centre
      address_line_1: Caldwell Rd
      address_town: Widnes
      address_postcode: WA8 7GD
      ods_code: N8M4W
    - name: Runcorn Shopping City
      address_line_1: Palacefields, Town square
      address_town: Runcorn
      address_postcode: WA7 2EU
      ods_code: null
    - name: Brookvale Family Hub
      address_line_1: Woodhatch Rd, Brookvale
      address_town: Runcorn
      address_postcode: WA7 6BJ
      ods_code: null
    - name: Warrington road family hub
      address_line_1: Naylor Rd
      address_town: Widnes
      address_postcode: WA8 0BS
      ods_code: null
    - name: Sutton Family Hub
      address_line_1: Ellamsbridge Road
      address_postcode: WA9 3PY
      ods_code: null
    - name: Newton Family Hub
      address_line_1: Patterson Street
      address_postcode: WA12 9PZ
      ods_code: null
    - name: Moss Bank Family hub
      address_line_1: Kentmere Avenue
      address_postcode: WA11 7PQ
      ods_code: null
    - name: Northwood Family Hub at The Pride Centre
      address_line_1: 2 Simonswood Lane
      address_postcode: L33 5YP
      ods_code: null
    - name: Jubilee Sure Start Childrens Centre
      address_line_1: Twig Lane
      address_postcode: L36 2LF
      ods_code: F2W7S
    - name: Hilltops Family Hub
      address_line_1: Bedford Close
      address_postcode: L36 1XH
      ods_code: Y1P4Y
    - name: New Hutte Children & Families Hub
      address_line_1: Lichfield Road
      address_postcode: L26 1TT
      ods_code: F2B7X
    - name: Thorn Road Clinic
      address_line_1: Thorn Rd
      address_town: Runcorn
      address_postcode: WA7 5HQ
      ods_code: D9U5I
    - name: St Johns Widnes
      address_line_1: Alforde St
      address_town: Widnes
      address_postcode: WA8 7QA
      ods_code: E0V8J
    - name: Kingsway Childrens Centre
      address_line_1: Victoria Square, Victoria Rd
      address_town: Widnes
      address_postcode: WA8 7QY
      ods_code: null
    - name: Windmill hill Family hub
      address_line_1: Norton Hill, Windmill Hill
      address_town: Runcorn
      address_postcode: WA7 6Q
      ods_code: null
    - name: Halton Lodge Family hub
      address_line_1: Grangeway, Halton Lodge
      address_town: Runcorn
      address_postcode: WA7 5LU
      ods_code: null
    - name: Ditton Community Centre
      address_line_1: 27 Dundalk Rd
      address_town: Widnes
      address_postcode: WA8 8DF
      ods_code: null
    - name: Sefton Road Family health clinic
      address_line_1: 67 Sefton Road
      address_town: Litherland
      address_postcode: L21 9HE
      ods_code: RW42E
    - name: Linaker Family Wellbeing Centre
      address_line_1: Sefton Street
      address_town: Southport
      address_postcode: PR8 5DQ
      ods_code: null
