organisation:
  ods_code: AJC

team:
  workgroup: vaccsuknewhamsais
  name: Vaccination UK - Newham
  email: newham@v-uk.co.uk
  phone: "0208 214 1396"
  careplus_venue_code: UNKNOWN
  privacy_policy_url: https://www.schoolvaccination.uk/privacy-policy
  privacy_notice_url: https://www.schoolvaccination.uk/policies
  reply_to_id: de2b1f20-5713-4f9f-b32d-798b99e0ecfc
  type: point_of_care

programmes: [menacwy, mmr, td_ipv, hpv]

subteams:
  newham:
    name: Vaccination UK - Newham
    email: newham@v-uk.co.uk
    phone: "0208 214 1396"
    reply_to_id: de2b1f20-5713-4f9f-b32d-798b99e0ecfc

schools:
  newham:
    - 102709
    - 102710
    - 134417
    - 144739
    - 136669
    - 102711
    - 144527
    - 102712
    - 130995
    - 143882
    - 102752
    - 149777
    - 145113
    - 144142
    - 149148
    - 102716
    - 143883
    - 145088
    - 136052
    - 148224
    - 141139
    - 143275
    - 102759
    - 145362
    - 102763
    - 143274
    - 143276
    - 145368
    - 102721
    - 102723
    - 102789
    - 138801
    - 145363
    - 139703
    - 149431
    - 142708
    - 141255
    - 143277
    - 102725
    - 144141
    - 132058
    - 140373
    - 102728
    - 148902
    - 102776
    - 142903
    - 134591
    - 102730
    - 145235
    - 145364
    - 145367
    - 134919
    - 146915
    - 141082
    - 102735
    - 102736
    - 132812
    - 152267
    - 142632
    - 134627
    - 144139
    - 144140
    - 148901
    - 102740
    - 145087
    - 145410
    - 143668
    - 102742
    - 130381
    - 142644
    - 138196
    - 148623
    - 145365
    - 142726
    - 145627
    - 141296
    - 132789
    - 102755
    - 102786
    - 148025
    - 102787
    - 147335
    - 147336
    - 141925
    - 102764
    - 141927
    - 102766
    - 150664
    - 102748
    - 148972
    - 102746
    - 102729
    - 136978
    - 143881
    - 102708
    - 142267
    - 145366
    - 102765
    - 102745
    - 102751
    - 102722
    - 134577

clinics:
  newham:
    - name: East Ham Library
      address_line_1: 328 Barking Rd
      address_town: London
      address_postcode: E6 2RT
    - name: Vicarage Lane
      address_line_1: 10 Vicarage Ln
      address_town: London
      address_postcode: E15 4ES
    - name: Woodgrange Medical Centre
      address_line_1: 40 Woodgrange Rd
      address_town: London
      address_postcode: E7 0QH
    - name: Shipman Family Hub
      address_line_1: 340 Prince Regent Ln
      address_town: London
      address_postcode: E16 3JH
    - name: Jack Cornwell Community Centre
      address_line_1: Jack Cornwell St
      address_town: London
      address_postcode: E12 5NN
    - name: Canning Town Library
      address_line_1: 18 Rathbone Market
      address_town: London
      address_postcode: E16 1EH
    - name: Beckton Globe Library
      address_line_1: 1 Kingsford Way
      address_town: London
      address_postcode: E6 5JQ
