organisation:
  name: XXX SMOKE TEST XXX
  email: england.mavis@nhs.net
  phone: "03003112233"
  ods_code: Y90128
  careplus_venue_code: SMOKE

programmes: [hpv]

teams:
  team1:
    name: XXX SMOKE TEST XXX
    email: xxx.smoke.test.xxx@example.nhs.net
    phone: "03003112233"

schools:
  team1:
    - XXXXXX

clinics:
  team1:
    - name: Test Clinic
      address_line_1: 1 Clinic Test Street
      address_town: Clinic Test Town
      address_postcode: TE1 1ST
      ods_code: XXXXX
