organisation:
  ods_code: AJC

team:
  workgroup: vaccsuktowerhamletssais
  name: Vaccination UK - Tower Hamlets
  email: towerhamlets@v-uk.co.uk
  phone: 0207 101 2026
  careplus_venue_code: UNKNOWN
  privacy_policy_url: https://www.schoolvaccination.uk/privacy-policy
  privacy_notice_url: https://www.schoolvaccination.uk/policies
  reply_to_id: c829e15d-3045-4b4f-a268-c0da63266053
  type: point_of_care

programmes:
  - menacwy
  - mmr
  - td_ipv
  - hpv

subteams:
  towerhamlets:
    name: Vaccination UK - Tower Hamlets
    email: towerhamlets@v-uk.co.uk
    phone: 0207 101 2026
    reply_to_id: c829e15d-3045-4b4f-a268-c0da63266053

schools:
  towerhamlets:
    - 133646
    - 130352
    - 100937
    - 100989
    - 100890
    - 100939
    - 150606
    - 150606
    - 100915
    - 100895
    - 100891
    - 100965
    - 100986
    - 149018
    - 138564
    - 144236
    - 142879
    - 137016
    - 141039
    - 100894
    - 100975
    - 100896
    - 100944
    - 150662
    - 100898
    - 140064
    - 148681
    - 131745
    - 139221
    - 100908
    - 100962
    - 135989
    - 100980
    - 100974
    - 100902
    - 100903
    - 100938
    - 100904
    - 131737
    - 151013
    - 143630
    - 131388
    - 100906
    - 100940
    - 100966
    - 133574
    - 100907
    - 134810
    - 100889
    - 141133
    - 132797
    - 100982
    - 134160
    - 100920
    - 100911
    - 100912
    - 100913
    - 133307
    - 100967
    - 100914
    - 137789
    - 148769
    - 143629
    - 144700
    - 144756
    - 149084
    - 100972
    - 140096
    - 100892
    - 100916
    - 100934
    - 139423
    - 147609
    - 100987
    - 100931
    - 137682
    - 138276
    - 100949
    - 150554
    - 100951
    - 150596
    - 100953
    - 100954
    - 131936
    - 100958
    - 143379
    - 143379
    - 100959
    - 100960
    - 100961
    - 144235
    - 131023
    - 100977
    - 100946
    - 100917
    - 100923
    - 100973
    - 144699
    - 139601
    - 100930
    - 151832
    - 138202
    - 100927
    - 100943
    - 100928
    - 143716

clinics:
  towerhamlets:
    - name: Gough Walk GP Practice
      address_line_1: 21 Newby Place
      address_town: Tower Hamlets
      address_postcode: E14 0EY
    - name: Suttons Wharf Health Centre
      address_line_1: 26 Palmers Road
      address_town: Tower Hamlets
      address_postcode: E2 0FA
    - name: East London Mosque
      address_line_1: 89-92 Whitechapel Road
      address_town: Tower Hamlets
      address_postcode: E1 1JQ
