organisation:
  ods_code: AJC

team:
  workgroup: vaccsukwalthamforestsais
  name: Vaccination UK - Waltham Forest
  email: walthamforest@v-uk.co.uk
  phone: "0208 017 4291"
  careplus_venue_code: UNKNOWN
  privacy_policy_url: https://www.schoolvaccination.uk/privacy-policy
  privacy_notice_url: https://www.schoolvaccination.uk/policies
  reply_to_id: 0079c885-539f-41f3-b32b-f6e9bca8c32e
  type: point_of_care

programmes: [menacwy, mmr, td_ipv, hpv]

subteams:
  walthamforest:
    name: Vaccination UK - Waltham Forest
    email: walthamforest@v-uk.co.uk
    phone: "0208 017 4291"
    reply_to_id: 0079c885-539f-41f3-b32b-f6e9bca8c32e

schools:
  walthamforest:
    - 131697
    - 140197
    - urn: 138454
      site: A
      name: "Lime Academy Hornbeam - Brookfield House"
      address_line_1: "Alders Avenue"
      address_town: "Woodford Green"
      address_postcode: "IG8 9PY"
    - urn: 138454
      site: B
      name: "Lime Academy Hornbeam- William Morris"
      address_line_1: "Folly Lane"
      address_town: "Walthamstow"
      address_postcode: "E17 5NT"
    - 103112
    - 140795
    - 130343
    - urn: 138690
      site: A
      name: "Barclay Primary School - Site 1"
      address_line_1: "155 Canterbury Road"
      address_town: "Leyton"
      address_postcode: "E10 6EJ"
    - urn: 138690
      site: B
      name: "Barclay Primary School - Site 2"
      address_line_1: "398A Hoe Street"
      address_town: "Walthamstow"
      address_postcode: "E17 9AA"
    - 131057
    - 137328
    - 103052
    - 139259
    - 103032
    - 103084
    - 103078
    - 143384
    - 103073
    - 103044
    - 103053
    - 138258
    - 103110
    - 103075
    - 103054
    - 103074
    - 103059
    - 137677
    - 135558
    - 103070
    - urn: 136413
      site: A
      name: "Hillyfield Primary Academy - Avelin Park Site"
      address_line_1: "Aveling Park Road"
      address_town: "Walthamstow"
      address_postcode: "E17 4NR"
    - urn: 136413
      site: B
      name: "Hillyfield Primary Academy - High Hill Road Site"
      address_line_1: "99-101 Higham Hill Road"
      address_town: "Walthamstow"
      address_postcode: "E17 6ED"
    - 141734
    - 147179
    - 142713
    - urn: 103077
      site: A
      name: "Mission Grove Primary School - North Site"
      address_line_1: "Buxton Road"
      address_town: "London"
      address_postcode: "E17 7EJ"
    - urn: 103077
      site: B
      name: "Mission Grove Primary School - South Site"
      address_line_1: "Edinburgh Road"
      address_town: "London"
      address_postcode: "E17 7QB"
    - 103048
    - 133517
    - 103069
    - 135193
    - 103081
    - 139723
    - 136362
    - 147180
    - 143383
    - 103072
    - 103090
    - 103086
    - 103085
    - 144238
    - 103088
    - 144239
    - 103079
    - 139724
    - 103082
    - 103061
    - urn: 139016
      site: A
      name: "The Woodside Primary Academy - Forest Site"
      address_line_1: "Wood Street"
      address_town: "Walthamstow"
      address_postcode: "E17 3JX"
    - urn: 139016
      site: B
      name: "The Woodside Primary Academy - Bridge Road Site"
      address_line_1: "Barrett Road"
      address_town: "Walthamstow"
      address_postcode: "E17 3ND"
    - 140405
    - 103060
    - 134579
    - 141748
    - 103036
    - 139317
    - 138364
    - 146681
    - 136364
    - 141030
    - 141411
    - 103080
    - 138691
    - 139293
    - 140957
    - 103094
    - urn: 145106
      site: A
      name: "George Mitchell School - Secondary"
      address_line_1: "Farmer Road"
      address_town: "Leyton"
      address_postcode: "E10 5DN"
    - urn: 145106
      site: B
      name: "George Mitchell School - Primary"
      address_line_1: "Byron Road"
      address_town: "London"
      address_postcode: "E10 5DT"
    - 103097
    - 137558
    - 103106
    - 103105
    - 145708
    - 132848
    - 103101
    - 143385
    - 138859
    - 132727
    - 103103
    - 103100

clinics:
  walthamforest:
    - name: Higham's Park Clinic
      address_line_1: 490 Larkshall Road
      address_town: Waltham Forest
      address_postcode: E4 9HH
    - name: Leystone United Free Church
      address_line_1: Leytonstone United Free Church
      address_line_2: 55 Wallwood Road
      address_town: Leytonstone
