basic_auth: Require users to sign in with basic authentication before they
  can use the service.

dev_tools: Developer tools useful for testing and debugging.

imms_api_integration: Umbrella flag to switch off ALL API integration (including CLI tools).

imms_api_search_job: Flag to switch off any automated receipt of vaccination records (Search),
  as part of the search job. This feature flag can be enabled on a per-organisation basis.

imms_api_sync_job: Flag to switch off any automated sending of vaccination records
  (Create, Update, Delete), triggered by the creation/edit/delete of any vaccination records.

import_choose_academic_year: Add an option to choose the academic year when
  importing patients during the preparation period.

import_low_pds_match_rate: Prevent processing uploads with a low pds match rate.

import_search_pds: Perform PDS lookups as part of the patient import processing.

import_review_screen: Enable the import review screen to allow users to review changesets
  before they are committed.

import_concurrency_per_server: |
  Controls whether to limit the concurrency of the import jobs to be global or
  to be per-server.

ops_tools: Enable the operational support tools; timeline and graph.

pds_cascading_search: Enable cascading PDS searches for patients without an NHS number.

statuses_changed_banner: Whether to show the banner outlining the changes to statuses.

tallying: Enables the session tally-based overview page

testing_api: Basic API useful for automated testing.

reporting_api: Enables the Commissioner reporting component to authenticate to Mavis via OAUTH 2.0
  Authorization Code Flow (https://datatracker.ietf.org/doc/html/rfc6749#section-4.1), and retrieve
  statistics from /api/reporting/
