# Flu

cell_based_trivalent:
  type: flu
  brand: Cell-based Trivalent Influenza Vaccine Seqirus
  method: injection
  manufacturer: Sequirus
  contains_gelatine: false
  upload_name: Sequirus Cell-based Trivalent
  nivs_name: Seqirus Cell-Based Trivalent IIVc
  dose_volume_ml: 0.5
  snomed_product_code: 43207411000001105
  snomed_product_term: Cell-based trivalent influenza vaccine (surface
    antigen, inactivated) suspension for injection 0.5ml pre-filled syringes
    (Seqirus UK Ltd)

fluenz:
  type: flu
  brand: Fluenz
  method: nasal
  manufacturer: AstraZeneca
  contains_gelatine: true
  upload_name: AstraZeneca Fluenz
  nivs_name: AstraZeneca Fluenz LAIV
  dose_volume_ml: 0.2
  snomed_product_code: 43208811000001106
  snomed_product_term: Fluenz (trivalent) vaccine nasal suspension 0.2ml unit
    dose (AstraZeneca UK Ltd) (product)

vaxigrip:
  type: flu
  brand: Vaxigrip
  method: injection
  manufacturer: Sanofi
  contains_gelatine: false
  upload_name: Sanofi Vaxigrip
  dose_volume_ml: 0.5
  snomed_product_code: 45175511000001104
  snomed_product_term: Vaxigrip Trivalent influenza vaccine (split virion,
    inactivated) suspension for injection 0.5ml pre-filled syringes (Sanofi)

viatris:
  type: flu
  brand: Viatris
  method: injection
  manufacturer: Viatris
  contains_gelatine: false
  upload_name: Viatris
  nivs_name: Viatris Quadrivalent Influvac sub - unit Tetra - QIVe
  dose_volume_ml: 0.5
  snomed_product_code: 45354911000001100
  snomed_product_term: Influenza TIV MYL vaccine suspension for injection
    0.5ml pre-filled syringes (Viatris UK Healthcare Ltd)

# HPV

cervarix:
  type: hpv
  brand: Cervarix
  discontinued: true
  method: injection
  manufacturer: GlaxoSmithKline
  contains_gelatine: false
  upload_name: Cervarix
  nivs_name: Cervarix
  dose_volume_ml: 0.5
  snomed_product_code: 12238911000001100
  snomed_product_term:
    Cervarix vaccine suspension for injection 0.5ml pre-filled
    syringes (GlaxoSmithKline) (product)

gardasil:
  type: hpv
  brand: Gardasil
  discontinued: true
  method: injection
  manufacturer: Merck Sharp & Dohme
  contains_gelatine: false
  upload_name: Gardasil
  nivs_name: Gardasil
  dose_volume_ml: 0.5
  snomed_product_code: 10880211000001104
  snomed_product_term:
    Gardasil vaccine suspension for injection 0.5ml pre-filled
    syringes (Merck Sharp & Dohme (UK) Ltd) (product)

gardasil_9:
  type: hpv
  brand: Gardasil 9
  method: injection
  manufacturer: Merck Sharp & Dohme
  contains_gelatine: false
  upload_name: Gardasil9
  nivs_name: Gardasil9
  dose_volume_ml: 0.5
  snomed_product_code: 33493111000001108
  snomed_product_term:
    Gardasil 9 vaccine suspension for injection 0.5ml pre-filled
    syringes (Merck Sharp & Dohme (UK) Ltd) (product)

# MenACWY

menquadfi:
  type: menacwy
  brand: MenQuadfi
  method: injection
  manufacturer: Sanofi
  contains_gelatine: false
  upload_name: MenQuadfi
  dose_volume_ml: 0.5
  snomed_product_code: 39779611000001104
  snomed_product_term:
    MenQuadfi vaccine solution for injection 0.5ml vials (Sanofi) (product)

menveo:
  type: menacwy
  brand: Menveo
  method: injection
  manufacturer: GlaxoSmithKline
  contains_gelatine: false
  upload_name: Menveo
  dose_volume_ml: 0.5
  snomed_product_code: 17188711000001105
  snomed_product_term:
    Menveo vaccine powder and solvent for solution for injection
    0.5ml vials (Novartis Vaccines and Diagnostics Ltd) (product)

nimenrix:
  type: menacwy
  brand: Nimenrix
  method: injection
  manufacturer: Pfizer
  contains_gelatine: false
  upload_name: Nimenrix
  dose_volume_ml: 0.5
  snomed_product_code: 20517811000001104
  snomed_product_term:
    Nimenrix vaccine powder and solvent for solution for injection
    0.5ml pre-filled syringes (GlaxoSmithKline UK Ltd) (product)

# MMR

priorix:
  type: mmr
  brand: Priorix
  method: injection
  manufacturer: GlaxoSmithKline
  contains_gelatine: false
  upload_name: Priorix
  dose_volume_ml: 0.5
  snomed_product_code: 34925111000001104
  snomed_product_term:
    Priorix vaccine powder and solvent for solution for injection
    0.5ml pre-filled syringes (GlaxoSmithKline UK Ltd) (product)

vaxpro:
  type: mmr
  brand: MMR VaxPro
  method: injection
  manufacturer: Merck Sharp & Dohme
  contains_gelatine: true
  upload_name: VaxPro
  dose_volume_ml: 0.5
  snomed_product_code: 13968211000001108
  snomed_product_term:
    M-M-RVAXPRO vaccine powder and solvent for suspension for injection
    0.5ml pre-filled syringes (Merck Sharp & Dohme (UK) Ltd) (product)

# Td/IPV

revaxis:
  type: td_ipv
  brand: Revaxis
  method: injection
  manufacturer: Sanofi
  contains_gelatine: false
  upload_name: Revaxis
  dose_volume_ml: 0.5
  snomed_product_code: 7374511000001107
  snomed_product_term:
    Revaxis vaccine suspension for injection 0.5ml pre-filled syringes
    (Sanofi) 1 pre-filled disposable injection (product)
