allow_dev_phone_numbers: true
disallow_database_seeding: false
fast_reset: true
web_concurrency: 0

cis2:
  enabled: false
  authentication_assurance_level: 1
  issuer: "https://am.nhsdev.auth-ptl.cis2.spineservices.nhs.uk:443/openam/oauth2/realms/root/realms/oidc"

mesh:
  base_url: https://localhost:8700
  disable_ssl_verification: true
  dps_mailbox: X26ABC3
  mailbox: X26ABC1

nhs_api:
  base_url: "https://sandbox.api.service.nhs.uk"
  disable_authentication: true

pds:
  perform_jobs: false
