allow_dev_phone_numbers: true
disallow_database_seeding: false

govuk_notify:
  mode: team

nhs_api:
  base_url: "https://int.api.service.nhs.uk"

# NHS Care Identity Service OIDC integration configuration, used by Omniauth via
# Devise.
cis2:
  issuer: "https://am.nhsint.auth-ptl.cis2.spineservices.nhs.uk:443/openam/oauth2/realms/root/realms/NHSIdentity/realms/Healthcare"

pds:
  raise_unknown_gp_practice: false
  rate_limit_per_second: 5
