name: Deploy

# on:
#   push:
#     branches: [main]

jobs:
  copilot:
    name: AWS Copilot deploy

    permissions:
      id-token: write
      contents: read

    environment:
      name: pentest
      url: https://${{ steps.host-name.outputs.value }}

    concurrency:
      group: pentest
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::393416225559:role/GitHubActionsRole
          aws-region: eu-west-2

      - name: Install and Verify AWS Copilot
        run: |
          curl -Lo /tmp/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x /tmp/copilot
          mv /tmp/copilot /usr/local/bin/copilot
          copilot --version

      - name: Deploy the application using AWS Copilot
        run: |
          copilot svc deploy --name webapp --env pentest

      - name: Get host name
        id: host-name
        run: |
          echo "value=pentest" >> $GITHUB_OUTPUT
