name: Deploy Documentation

on:
  push:
    branches:
      - release
      - next

permissions:
  contents: write

jobs:
  deploy-documentation:
    name: Generate and Publish RDoc
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-documentation-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Generate Documentation
        run: bundle exec rake rdocs:generate

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/rdoc
          target-folder: docs/rdoc/${{ github.ref_name }}
          clean: false
